http:
  routers:
    cockpit:
      rule: "Host(`cockpit.bumblebee.favarohome.com`)"
      entryPoints:
        - websecure
      service: cockpit
      tls:
        certResolver: cloudflare

  services:
    cockpit:
      loadBalancer:
        servers:
          - url: "https://192.168.1.14:9090"
        serversTransport: insecureTransport

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
